#version: "3.8" -> warning de obsoleto

services:
  usuarios:
    build:
      context: .
      dockerfile: usuarios/Dockerfile
    ports:
      - "8000:8000"
#    volumes:
#      - ./usuarios:/app/usuarios